
---
- name: Copy the exploitdog_agent service file
  template:
    src: "exploitdog_agent.{{ ansible_service_mgr | lower }}.j2"
    dest: "{{ lookup('vars', '_exploitdog_agent_' + ansible_service_mgr + '_service').file }}"
    owner: root
    group: root
    mode: "{{ lookup('vars', '_exploitdog_agent_' + ansible_service_mgr + '_service').mode }}"
  notify: "restart exploitdog_agent"