---
- import_tasks: preflight.yml
  tags:
    - exploitdog_agent_install
    - exploitdog_agent_configure
    - exploitdog_agent_run

- import_tasks: install.yml
  become: true
  tags:
    - exploitdog_agent_install

- import_tasks: configure.yml
  become: true
  tags:
    - exploitdog_agent_configure

- name: Ensure ExplotDog agent service is enabled on boot
  become: true
  service:
    name: exploitdog_agent
    enabled: true
    state: started
  when: ansible_service_mgr != 'systemd' and not ansible_check_mode
  tags:
    - exploitdog_agent_run

- name: Ensure ExplotDog agent systemd service is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: exploitdog_agent
    enabled: true
    state: started
  when: ansible_service_mgr == 'systemd' and not ansible_check_mode
  tags:
    - exploitdog_agent_run

#- name: Restart everything
#  command: echo "this task will restart the web services"
#  notify: "restart exploitdog_agent"