---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bionic
    image: mpaivabarbosa/molecule-systemd-ubuntu:18.04
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
  - name: xenial
    image: mpaivabarbosa/molecule-systemd-ubuntu:20.04
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
  - name: stretch
    image: mpaivabarbosa/molecule-systemd-debian:9
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
  - name: buster
    image: mpaivabarbosa/molecule-systemd-debian:10
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
#  - name: centos7
#    image: mpaivabarbosa/molecule-systemd-centos:7
#    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
#    privileged: true
#    pre_build_image: true
#    override_command: false
#    cgroupns_mode: host
#    security_opts:
#      - seccomp=unconfined
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:rw
#    tmpfs:
#      - /run
#      - /tmp
#    groups:
#      - python3
  - name: centos8
    image: mpaivabarbosa/molecule-systemd-centos:8
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    privileged: true
    pre_build_image: true
    override_command: false
    cgroupns_mode: host
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    groups:
      - python3

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: testinfra
